### ISSUE TITLE
SL Review: Explore Landing page for SL Review form users

### ISSUE THREAD

**Issue by HasanSifat** [alexandralloyd/DJ-program#15]
**User Story**
As a SL, we need a landing page to access the form and get information on the whole process for SL review.

**Tasks**

- [ ] Engage the content team to start exploring the content for this landing page

- [ ] consult with SL team to finalize content 

- [ ] Create page in QA

- [ ] Launch page

**Acceptance Criteria**
Once all the checklist items are completed and checked-off

**Comment by MeghanStothers** [comment]
Great to start thinking about the content and engaging the Careers & MyHR content team. As a first step, The SL team will need to connect with PIE (Andrea Gillis) about working on a (corporate or Agency-focused) communications plan. They can help draft key messages and so on.
